from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.units import inch
from datetime import datetime
import io

def export_chat_to_pdf(messages: list) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=HexColor('#6e56cf'),
        spaceAfter=4,
        fontName='Helvetica-Bold'
    )

    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=HexColor('#8b949e'),
        spaceAfter=20,
    )

    user_label_style = ParagraphStyle(
        'UserLabel',
        parent=styles['Normal'],
        fontSize=9,
        textColor=HexColor('#6e56cf'),
        fontName='Helvetica-Bold',
        spaceAfter=4,
    )

    bot_label_style = ParagraphStyle(
        'BotLabel',
        parent=styles['Normal'],
        fontSize=9,
        textColor=HexColor('#3fb950'),
        fontName='Helvetica-Bold',
        spaceAfter=4,
    )

    user_style = ParagraphStyle(
        'UserMsg',
        parent=styles['Normal'],
        fontSize=11,
        textColor=HexColor('#e6edf3'),
        backColor=HexColor('#6e56cf'),
        borderPadding=(8, 10, 8, 10),
        spaceAfter=12,
        borderRadius=8,
    )

    bot_style = ParagraphStyle(
        'BotMsg',
        parent=styles['Normal'],
        fontSize=11,
        textColor=HexColor('#1c2128'),
        backColor=HexColor('#f0f2f4'),
        borderPadding=(8, 10, 8, 10),
        spaceAfter=4,
        borderRadius=8,
    )

    source_style = ParagraphStyle(
        'Source',
        parent=styles['Normal'],
        fontSize=9,
        textColor=HexColor('#6e56cf'),
        fontName='Helvetica-Oblique',
        leftIndent=20,
        spaceAfter=12,
    )

    story = []

    # Header
    story.append(Paragraph("RAG Platform", title_style))
    story.append(Paragraph(
        f"Document Intelligence — Chat Export · {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        subtitle_style
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=HexColor('#30363d')))
    story.append(Spacer(1, 16))

    # Messages
    for msg in messages:
        if msg.get('role') == 'user':
            story.append(Paragraph("YOU", user_label_style))
            story.append(Paragraph(msg.get('text', ''), user_style))
        elif msg.get('role') == 'bot':
            story.append(Paragraph("AI ASSISTANT", bot_label_style))
            story.append(Paragraph(msg.get('text', ''), bot_style))
            if msg.get('sources'):
                for src in msg['sources'][:2]:
                    story.append(Paragraph(
                        f"📄 Source: {src.get('source', '')}",
                        source_style
                    ))
        story.append(Spacer(1, 4))

    # Footer
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=HexColor('#30363d')))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        f"Generated by RAG Document Intelligence Platform · {datetime.now().strftime('%Y')}",
        subtitle_style
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()